repos:
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --allow-untyped-decorators, --install-types, --non-interactive]
